name: Statics

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12",]
        # python-version: ["3.8.1", "3.9.1", "3.10.12", "3.11.1", "3.12.1"]
        poetry-version: ["1.7.0"]
        # pandas-version: ["2.2.0", "2.1.0", "2.0.0", "1.5.0", "1.4.0", "1.3.0"]
        # scikit-learn-version: ["1.4.0", "1.3.0", "1.2.0", "1.1.0", "1.0",]

    # runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: poetry Install
        run: poetry install

      - name: Run black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check-only --profile black

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run bandit
        run: poetry run bandit .

      - name: Run saftey
        run: poetry run safety check